/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
     @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
* and open th    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
e template in the editor.
 */
package ies.sauces.agenciaalquiler.vista;

import ies.sauces.agenciaalquiler.controlador.Controlador;
import ies.sauces.agenciaalquiler.modelo.Vehiculo;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Usuario
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form ventana
     */
    public Ventana() {
        initComponents();
    }

    private DialogoVehiculo dialogoVehiculo = new DialogoVehiculo(this, true);
    private Controlador controlador;
    private VehiculoTableModel vehiculoTM;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorFichero = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        etiquetaMatricula = new javax.swing.JLabel();
        textoMatricula = new javax.swing.JTextField();
        etiquetaGrupo = new javax.swing.JLabel();
        comboBoxGrupo = new javax.swing.JComboBox<>();
        etiquetaTipo = new javax.swing.JLabel();
        comboBoxTipo = new javax.swing.JComboBox<>();
        etiquetaPlazas = new javax.swing.JLabel();
        spinnerPlazas = new javax.swing.JSpinner();
        etiquetaCapacidad = new javax.swing.JLabel();
        etiquetaPrecioDia = new javax.swing.JLabel();
        jFormattedTextFieldPrecioDia = new javax.swing.JFormattedTextField();
        botonBorrar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botonVehiculoBarato = new javax.swing.JButton();
        botonVehiculoCaro = new javax.swing.JButton();
        jFormattedTextFieldCapacidad = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        botonListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        etiquetaOrdenListado = new javax.swing.JLabel();
        radioButtonMatricula = new javax.swing.JRadioButton();
        jRadioButtonPrecioAlquiler = new javax.swing.JRadioButton();
        etiquetaFiltrarGrupo = new javax.swing.JLabel();
        comboBoxFiltrarGrupo = new javax.swing.JComboBox<>();
        etiquetaFiltrarTipo = new javax.swing.JLabel();
        comboBoxFiltrarTipo = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenuItemGuardar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();
        jMenuVehiculo = new javax.swing.JMenu();
        jMenuItemNuevo = new javax.swing.JMenuItem();
        jMenuItemBuscar = new javax.swing.JMenuItem();
        menuExamen = new javax.swing.JMenu();
        menuItemConsultar = new javax.swing.JMenuItem();
        menuItemNumeroTurismos = new javax.swing.JMenuItem();
        menuItemCapacidad = new javax.swing.JMenuItem();
        menuItemMasPlazas = new javax.swing.JMenuItem();

        selectorFichero.setCurrentDirectory(new java.io.File("."));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agencia de alquiler de vehiculos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del vehículo"));
        jPanel1.setEnabled(false);

        etiquetaMatricula.setText("MATRÍCULA");

        textoMatricula.setEditable(false);

        etiquetaGrupo.setText("GRUPO");

        comboBoxGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        comboBoxGrupo.setEnabled(false);

        etiquetaTipo.setText("TIPO");

        comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "TURISMO", "FURGONETA" }));
        comboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoActionPerformed(evt);
            }
        });

        etiquetaPlazas.setText("PLAZAS");

        etiquetaCapacidad.setText("CAPACIDAD");

        etiquetaPrecioDia.setText("PRECIO POR DÍA");

        jFormattedTextFieldPrecioDia.setEditable(false);
        jFormattedTextFieldPrecioDia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        botonBorrar.setText("BORRAR");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonModificar.setText("MODIFICAR");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Otras operaciones"));

        botonVehiculoBarato.setText("MOSTRAR VEHÍCULO MÁS BARATO");
        botonVehiculoBarato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVehiculoBaratoActionPerformed(evt);
            }
        });

        botonVehiculoCaro.setText("MOSTRAR VEHÍCULO MÁS CARO");
        botonVehiculoCaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVehiculoCaroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonVehiculoCaro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVehiculoBarato, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(botonVehiculoBarato)
                .addGap(18, 18, 18)
                .addComponent(botonVehiculoCaro)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jFormattedTextFieldCapacidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonModificar))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(etiquetaPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(spinnerPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(etiquetaGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiquetaMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(textoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(etiquetaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(etiquetaPrecioDia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiquetaCapacidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldPrecioDia)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jFormattedTextFieldCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaMatricula)
                    .addComponent(textoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaGrupo)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBoxGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiquetaTipo)
                        .addComponent(comboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPlazas)
                    .addComponent(spinnerPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCapacidad)
                    .addComponent(jFormattedTextFieldCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPrecioDia)
                    .addComponent(jFormattedTextFieldPrecioDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrar)
                    .addComponent(botonModificar))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de vehículos"));

        botonListar.setText("LISTAR VEHÍCULOS");
        botonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarActionPerformed(evt);
            }
        });

        vehiculoTM=new VehiculoTableModel();
        tablaVehiculos.setModel(vehiculoTM);
        tablaVehiculos.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent lse){
                int fila=tablaVehiculos.getSelectedRow();
                if(fila>=0){
                    mostrarMatricula(tablaVehiculos.getValueAt(fila, 0).toString());
                    mostrarGrupo(tablaVehiculos.getValueAt(fila,1).toString());
                    String tipo=tablaVehiculos.getValueAt(fila, 2).toString();
                    mostrarTipo(tipo);
                    if(tipo.equals("TURISMO")){
                        mostrarPlazas((int)tablaVehiculos.getValueAt(fila, 3));
                        mostrarCapacidad(0);
                    }else{
                        mostrarCapacidad((float)tablaVehiculos.getValueAt(fila, 4));
                        mostrarPlazas(0);
                    }
                    mostrarPrecioAlquiler((float)tablaVehiculos.getValueAt(fila, 5));
                }
            }
        }
    );
    jScrollPane1.setViewportView(tablaVehiculos);

    etiquetaOrdenListado.setText("ORDEN DEL LISTADO");

    buttonGroup1.add(radioButtonMatricula);
    radioButtonMatricula.setSelected(true);
    radioButtonMatricula.setText("MATRÍCULA");
    radioButtonMatricula.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            radioButtonMatriculaActionPerformed(evt);
        }
    });

    buttonGroup1.add(jRadioButtonPrecioAlquiler);
    jRadioButtonPrecioAlquiler.setText("PRECIO ALQUILER");

    etiquetaFiltrarGrupo.setLabelFor(comboBoxFiltrarGrupo);
    etiquetaFiltrarGrupo.setText("FILTRAR POR GRUPO");

    comboBoxFiltrarGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "A", "B", "C" }));

    etiquetaFiltrarTipo.setText("FILTRAR POR TIPO");

    comboBoxFiltrarTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "TURISMO", "FURGONETA" }));
    comboBoxFiltrarTipo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            comboBoxFiltrarTipoActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(275, 275, 275)
                    .addComponent(botonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(radioButtonMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(49, 49, 49)
                    .addComponent(jRadioButtonPrecioAlquiler))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(etiquetaOrdenListado, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(103, 103, 103)
                    .addComponent(etiquetaFiltrarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(comboBoxFiltrarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(etiquetaFiltrarTipo)
                    .addGap(18, 18, 18)
                    .addComponent(comboBoxFiltrarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(56, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(botonListar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)
                    .addComponent(etiquetaOrdenListado, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etiquetaFiltrarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboBoxFiltrarGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiquetaFiltrarTipo)
                        .addComponent(comboBoxFiltrarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(radioButtonMatricula)
                .addComponent(jRadioButtonPrecioAlquiler))
            .addGap(70, 70, 70))
    );

    jMenuArchivo.setText("Archivo");

    jMenuItemAbrir.setText("Abrir...");
    jMenuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemAbrirActionPerformed(evt);
        }
    });
    jMenuArchivo.add(jMenuItemAbrir);

    jMenuItemGuardar.setText("Guardar...");
    jMenuItemGuardar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemGuardarActionPerformed(evt);
        }
    });
    jMenuArchivo.add(jMenuItemGuardar);
    jMenuArchivo.add(jSeparator1);

    salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
    salir.setText("Salir...");
    salir.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            salirActionPerformed(evt);
        }
    });
    jMenuArchivo.add(salir);

    jMenuBar1.add(jMenuArchivo);

    jMenuVehiculo.setText("Vehiculo");

    jMenuItemNuevo.setText("Nuevo...");
    jMenuItemNuevo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemNuevoActionPerformed(evt);
        }
    });
    jMenuVehiculo.add(jMenuItemNuevo);

    jMenuItemBuscar.setText("Buscar...");
    jMenuItemBuscar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemBuscarActionPerformed(evt);
        }
    });
    jMenuVehiculo.add(jMenuItemBuscar);

    jMenuBar1.add(jMenuVehiculo);

    menuExamen.setText("Examen");

    menuItemConsultar.setText("Consultar lprecio");
    menuItemConsultar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuItemConsultarActionPerformed(evt);
        }
    });
    menuExamen.add(menuItemConsultar);

    menuItemNumeroTurismos.setText("Número de turismos");
    menuExamen.add(menuItemNumeroTurismos);

    menuItemCapacidad.setText("Capacidad media");
    menuExamen.add(menuItemCapacidad);

    menuItemMasPlazas.setText("Turismo con más plazas");
    menuItemMasPlazas.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            menuItemMasPlazasActionPerformed(evt);
        }
    });
    menuExamen.add(menuItemMasPlazas);

    jMenuBar1.add(menuExamen);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirActionPerformed
        if (selectorFichero.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            controlador.cargarVehiculos();
        }
    }//GEN-LAST:event_jMenuItemAbrirActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        String matricula = JOptionPane.showInputDialog("Introduce la matricula del vehiculo a borrar");
        mostrarMatricula(matricula);
        if (matricula != null) {
            if (!matricula.isBlank()) {
                if (solicitarConfirmacion()) {
                    controlador.borrarVehiculo();
                }
            }
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        String matricula = JOptionPane.showInputDialog("Introduce la matricula del vehiculo a modificar");
        mostrarMatricula(matricula);
        if (matricula != null) {
            if (!matricula.isBlank()) {
                if (solicitarConfirmacion()) {
                    controlador.modificarVehiculo();
                }
            }
        }

    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarActionPerformed
        controlador.listarVehiculos();
    }//GEN-LAST:event_botonListarActionPerformed

    private void comboBoxFiltrarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxFiltrarTipoActionPerformed

    }//GEN-LAST:event_comboBoxFiltrarTipoActionPerformed

    private void jMenuItemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoActionPerformed
        dialogoVehiculo.limpiarCampos();
        if (dialogoVehiculo.mostrar() == DialogoVehiculo.ACEPTAR) {
            mostrarMatricula(dialogoVehiculo.getMatricula());
            mostrarGrupo(dialogoVehiculo.getGrupo());
            String tipo = dialogoVehiculo.getTipo();
            mostrarTipo(tipo);
            if (tipo.equals("TURISMO")) {
                mostrarPlazas(dialogoVehiculo.getPlazas());
            } else {
                mostrarCapacidad(dialogoVehiculo.getCapacidad());
            }
            controlador.crearVehiculo();
        }
    }//GEN-LAST:event_jMenuItemNuevoActionPerformed

    private void jMenuItemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGuardarActionPerformed
        if (selectorFichero.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            controlador.guardarVehiculos();
        }
    }//GEN-LAST:event_jMenuItemGuardarActionPerformed

    private void jMenuItemBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarActionPerformed
        mostrarMatricula(JOptionPane.showInputDialog("Introduzca matrícula para buscar vehículo"));
        controlador.buscarVehiculo();
    }//GEN-LAST:event_jMenuItemBuscarActionPerformed

    private void botonVehiculoBaratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVehiculoBaratoActionPerformed
        controlador.buscarVehiculoMasBarato();
    }//GEN-LAST:event_botonVehiculoBaratoActionPerformed

    private void botonVehiculoCaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVehiculoCaroActionPerformed
        controlador.buscarVehiculoMasCaro();
    }//GEN-LAST:event_botonVehiculoCaroActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void radioButtonMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonMatriculaActionPerformed

    }//GEN-LAST:event_radioButtonMatriculaActionPerformed

    private void comboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoActionPerformed
        if (comboBoxTipo.getSelectedItem().equals("TURISMO")) {
            etiquetaCapacidad.setVisible(false);
            jFormattedTextFieldCapacidad.setVisible(false);
            etiquetaPlazas.setVisible(true);
            spinnerPlazas.setVisible(true);
        } else if (comboBoxTipo.getSelectedItem().equals("FURGONETA")) {
            etiquetaCapacidad.setVisible(true);
            jFormattedTextFieldCapacidad.setVisible(true);
            etiquetaPlazas.setVisible(false);
            spinnerPlazas.setVisible(false);
        }
    }//GEN-LAST:event_comboBoxTipoActionPerformed

    private void menuItemMasPlazasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMasPlazasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemMasPlazasActionPerformed

    private void menuItemConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultarActionPerformed
        controlador.consultarPrecio();
    }//GEN-LAST:event_menuItemConsultarActionPerformed

    public String getMatricula() {
        return textoMatricula.getText();
    }

    public String getGrupo() {
        return comboBoxGrupo.getSelectedItem().toString();
    }

    public String getTipo() {
        return comboBoxTipo.getSelectedItem().toString();
    }

    public int getPlazas() {
        return (int) spinnerPlazas.getValue();
    }

    public float getCapacidad() {
        return Float.parseFloat(this.jFormattedTextFieldCapacidad.getText().replace(',', '.'));
    }

    public String getArchivo() {
        return selectorFichero.getSelectedFile().getAbsolutePath();
    }

    public String getOrden() {
        if (radioButtonMatricula.isSelected()) {
            return "MATRICULA";
        } else {
            return "ALQUILER";
        }
    }

    public String getFiltroGrupo() {
        return comboBoxFiltrarGrupo.getSelectedItem().toString();
    }

    public String getFiltroTipo() {
        return comboBoxFiltrarTipo.getSelectedItem().toString();
    }

    public void mostrarMatricula(String matricula) {
        textoMatricula.setText(matricula);
    }

    public void mostrarTipo(String tipo) {
        comboBoxTipo.setSelectedItem(tipo);
    }

    public void mostrarGrupo(String grupo) {
        comboBoxGrupo.setSelectedItem(grupo);
    }

    public void mostrarPlazas(int plazas) {
        spinnerPlazas.setValue(plazas);
    }

    public void mostrarCapacidad(float capacidad) {
        jFormattedTextFieldCapacidad.setValue(capacidad);
    }

    public void mostrarPrecioAlquiler(float precio) {
        jFormattedTextFieldPrecioDia.setValue(precio);
    }

    public void listarVehiculos(List<Vehiculo> listado) {
        vehiculoTM.setListadoVehiculos(listado);
        vehiculoTM.fireTableDataChanged();
    }

    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
    }

    public boolean solicitarConfirmacion() {
        if (JOptionPane.showConfirmDialog(this, "Confirmar", "¿Confirmar operación?", JOptionPane.YES_NO_CANCEL_OPTION) == JOptionPane.YES_OPTION) {
            return true;
        } else {
            return false;
        }
    }

    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    public void limpiarCampos() {
        mostrarMatricula(" ");
        comboBoxGrupo.setSelectedIndex(0);
        mostrarPlazas(0);
        comboBoxTipo.setSelectedIndex(0);
        mostrarCapacidad(0);
        mostrarPrecioAlquiler(0);
    }

    public void mostrar() {
        limpiarCampos();
        setVisible(true);
    }

    public void actualizarTabla() {
        vehiculoTM.fireTableDataChanged();
    }
    
    public String getEntradaExamen(){
        return JOptionPane.showInputDialog(this,"Introduzca texto");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonListar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonVehiculoBarato;
    private javax.swing.JButton botonVehiculoCaro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxFiltrarGrupo;
    private javax.swing.JComboBox<String> comboBoxFiltrarTipo;
    private javax.swing.JComboBox<String> comboBoxGrupo;
    private javax.swing.JComboBox<String> comboBoxTipo;
    private javax.swing.JLabel etiquetaCapacidad;
    private javax.swing.JLabel etiquetaFiltrarGrupo;
    private javax.swing.JLabel etiquetaFiltrarTipo;
    private javax.swing.JLabel etiquetaGrupo;
    private javax.swing.JLabel etiquetaMatricula;
    private javax.swing.JLabel etiquetaOrdenListado;
    private javax.swing.JLabel etiquetaPlazas;
    private javax.swing.JLabel etiquetaPrecioDia;
    private javax.swing.JLabel etiquetaTipo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCapacidad;
    private javax.swing.JFormattedTextField jFormattedTextFieldPrecioDia;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuItemBuscar;
    private javax.swing.JMenuItem jMenuItemGuardar;
    private javax.swing.JMenuItem jMenuItemNuevo;
    private javax.swing.JMenu jMenuVehiculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonPrecioAlquiler;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuExamen;
    private javax.swing.JMenuItem menuItemCapacidad;
    private javax.swing.JMenuItem menuItemConsultar;
    private javax.swing.JMenuItem menuItemMasPlazas;
    private javax.swing.JMenuItem menuItemNumeroTurismos;
    private javax.swing.JRadioButton radioButtonMatricula;
    private javax.swing.JMenuItem salir;
    private javax.swing.JFileChooser selectorFichero;
    private javax.swing.JSpinner spinnerPlazas;
    private javax.swing.JTable tablaVehiculos;
    private javax.swing.JTextField textoMatricula;
    // End of variables declaration//GEN-END:variables

}
